# Generated by Django 3.0.4 on 2020-03-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
            preserve_default=False,
        ),
    ]
